name: Merge cantonal CSVs

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    # Runs a single command using the runners shell
    - name: Print header line and then merge all files without header line
      run: ruby scripts/merge_canton_csvs.rb > COVID19_Fallzahlen_CH_total_v2.csv

    # Create v2 files
    - name: Create v1 files based on new structure
      run: |
        ./scripts/transform_all_new2old.sh
        ./scripts/new2oldcsv.py COVID19_Fallzahlen_CH_total_v2.csv > COVID19_Fallzahlen_CH_total.csv

    # update screenshot of dashboard
    - name: Screenshot Dashboard
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://www.web.statistik.zh.ch/covid19_dashboard/index.html#/
        destination: dashboard.png
        full-page: true
        delay: 5
    
    # download artifact
    - name: Download dashboard screenshot from last step
      uses: actions/download-artifact@v1
      with:
        name: dashboard

    # Commit to repo with updated file
    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Update COVID19_Fallzahlen_CH_total.csv
        branch: ${{ github.head_ref }}
