name: Run scrapers

on:
  schedule:
    - cron:  '5-59/15 * * * *' # run at 5', 20', 35', 50'

jobs:
  run_scraper:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        canton:
          - AG
          - AI
          - AR
          - BE
          - BS
          - FR
          - GL
          - GR
          - JU
          - LU
          - NE
          - NW
          - OW
          - SG
          - SH
          - SO
          # - SZ
          - TG
          - TI
          - UR
          - VD
          - VS
          - ZG
        allow-failure: [false]
        include:
          - python-version: 3.7
            canton: FR
            overwrite: yes

          - python-version: 3.7
            canton: GL
            overwrite: yes

          - python-version: 3.7
            canton: GR
            overwrite: yes

          - python-version: 3.7
            canton: JU
            overwrite: yes

          - python-version: 3.7
            canton: LU
            overwrite: yes

          - python-version: 3.7
            canton: NE
            overwrite: yes

          - python-version: 3.7
            canton: SH
            overwrite: yes

          - python-version: 3.7
            canton: SO
            overwrite: yes

          #- python-version: 3.7
          #  canton: SZ
          #  overwrite: yes

          - python-version: 3.7
            canton: TI
            overwrite: yes

          - python-version: 3.7
            canton: VD
            source: https://www.vd.ch/toutes-les-actualites/hotline-et-informations-sur-le-coronavirus/point-de-situation-statistique-dans-le-canton-de-vaud/
            overwrite: yes

          - python-version: 3.7
            canton: VS
            source: https://www.vs.ch/de/web/coronavirus
            overwrite: yes

          - python-version: 3.7
            canton: ZG
            source: https://www.zg.ch/behoerden/gesundheitsdirektion/statistikfachstelle/themen/gesundheit/corona
            overwrite: yes

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - run: npm ci
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install sqlite3 poppler-utils

    - name: Scrape new data
      env:
        SCRAPER_KEY: ${{ matrix.canton }}
        SCRAPER_SOURCE: ${{ matrix.source }}
        SCRAPER_OVERWRITE: ${{ matrix.overwrite }}
      run: |
        ./scrapers/run_scraper.sh
    
    - name: Commit and push to repo
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: master
        name: GitHub Action Scraper
        email: scraper@open.zh.ch
        commit-message: Update COVID19_Fallzahlen_Kanton_${{ matrix.canton }}_total.csv from scraper
        rebase: 'true'
